# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef7d302c5bfc3d881c779a75b07fafefec10dbdea978e2f618cbc93f0194d34c6e7e7ba4e6186399265b5beea34b34b1e33a3d4a7214e89dabd4083ed010d21c

test:
  secret_key_base: d79165fc8573cd1f9e591eb39b5a594b481276a1199548de77252d958c9ec712bda4e24b0a2d0d908aadf3d9316ceb20e0a6f28e0ed257e0d1e137315d811c8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
